export const myApps = [
  {
    _id: "appID",
    type: "editor",
    appIconText: " ✨ Editor",
  },
  {
    _id: "appID",
    type: "previewer",
    appIconText: " 🖼️ Final Output",
  },
  // {
  //   _id: "appID",
  //   type: "previewer2",
  //   appIconText: " 🖼️ Previewer 2",
  // },
  // {
  //   _id: "appID",
  //   type: "files",
  //   appIconText: " 🖼️ Files",
  // },
];

export const myWins = [
  {
    _id: "winID",
    appID: "appID",
    type: "editor",
    title: ` ✨ Editor`,
    top: 10,
    left: 10,
    width: 300,
    height: 300,
    zIndex: 0,
  },
  {
    _id: "winID",
    appID: "appID",
    type: "previewer",
    title: ` 🖼️ Final Output`,
    top: 20,
    left: 20,
    width: 300,
    height: 300,
    zIndex: 0,
  },
  {
    _id: "winID",
    appID: "appID",
    type: "previewer2",
    title: ` 🖼️ Previewer 2`,
    top: 20,
    left: 20,
    width: 300,
    height: 300,
    zIndex: 0,
  },
  {
    _id: "winID",
    appID: "appID",
    type: "coder",
    title: ` 👨🏼‍💻 Coder`,
    top: 20,
    left: 20,
    width: 600,
    height: 500,
    zIndex: 0,
    data: {},
  },
  // {
  //   _id: "winID",
  //   appID: "appID",
  //   type: "files",
  //   title: ` 🗂️ Files`,
  //   top: 20,
  //   left: 20,
  //   width: 600,
  //   height: 500,
  //   zIndex: 0,
  //   data: {},
  // },
];
