import type { Metadata } from "next";
import {
  JetBrains_Mono,
  Plus_Jakarta_Sans,
  Space_Grotesk,
} from "next/font/google";

import "./globals.css";

const headings = Space_Grotesk({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
const body = Plus_Jakarta_Sans({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});
const code = JetBrains_Mono({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${headings.className} ${body.className} ${code.className}`}
      >
        <style
          dangerouslySetInnerHTML={{
            __html: `
:root {
  --font-sans: ${body.style.fontFamily}, ui-sans-serif, system-ui, sans-serif;
  --font-mono: ${code.style.fontFamily}, ui-monospace, SFMono-Regular, monospace;
  --font-serif: ${headings.style.fontFamily}, Cambria, "Times New Roman", serif;
}
.dark {
  --font-sans: ${body.style.fontFamily}, ui-sans-serif, system-ui, sans-serif;
  --font-mono: ${code.style.fontFamily}, ui-monospace, SFMono-Regular, monospace;
  --font-serif: ${headings.style.fontFamily}, Cambria, "Times New Roman", serif;
}
          `,
          }}
        ></style>
        {children}
      </body>
    </html>
  );
}
